### ISSUE TITLE
AttributeError: 'module" object has no attribute 'layer_providers'

### ISSUE THREAD

**Issue by digitaldatasvcs** [cartologic/cartoview_arcgis_feature_server#1]
We are trying to install the ArcGIS Feature Server. CartoView installs fine, both with SQLite and PostgreSQL. When we add the ArcGIS Feature Server App, CartoView breaks with an Internal Server Error (Geonode and Geoserver are fine). Any ideas on how to resolve?

From Log:
`[Mon Aug 15 14:05:10.925962 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155] mod_wsgi (pid=81364): Exception occurred processing WSGI script 'C:/Program Files (x86)/Cartoview/Cartoview/cartoview/wsgi.py'.
[Mon Aug 15 14:05:10.925962 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155] Traceback (most recent call last):
[Mon Aug 15 14:05:10.925962 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]   File "C:\\Program Files (x86)\\Cartoview\\Python\\lib\\site-packages\\django-1.6.11-py2.7.egg\\django\\core\\handlers\\wsgi.py", line 187, in __call__
[Mon Aug 15 14:05:10.926962 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]     self.load_middleware()
[Mon Aug 15 14:05:10.926962 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]   File "C:\\Program Files (x86)\\Cartoview\\Python\\lib\\site-packages\\django-1.6.11-py2.7.egg\\django\\core\\handlers\\base.py", line 47, in load_middleware
[Mon Aug 15 14:05:10.926962 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]     mw_instance = mw_class()
[Mon Aug 15 14:05:10.926962 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]   File "C:\\Program Files (x86)\\Cartoview\\Python\\lib\\site-packages\\django-1.6.11-py2.7.egg\\django\\middleware\\locale.py", line 24, in __init__
[Mon Aug 15 14:05:10.927962 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]     for url_pattern in get_resolver(None).url_patterns:
[Mon Aug 15 14:05:10.927962 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]   File "C:\\Program Files (x86)\\Cartoview\\Python\\lib\\site-packages\\django-1.6.11-py2.7.egg\\django\\core\\urlresolvers.py", line 365, in url_patterns
[Mon Aug 15 14:05:10.928962 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
[Mon Aug 15 14:05:10.928962 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]   File "C:\\Program Files (x86)\\Cartoview\\Python\\lib\\site-packages\\django-1.6.11-py2.7.egg\\django\\core\\urlresolvers.py", line 360, in urlconf_module
[Mon Aug 15 14:05:10.928962 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]     self._urlconf_module = import_module(self.urlconf_name)
[Mon Aug 15 14:05:10.928962 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]   File "C:\\Program Files (x86)\\Cartoview\\Python\\lib\\site-packages\\django-1.6.11-py2.7.egg\\django\\utils\\importlib.py", line 40, in import_module
[Mon Aug 15 14:05:10.928962 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]     __import__(name)
[Mon Aug 15 14:05:10.929962 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]   File "C:\\Program Files (x86)\\Cartoview\\cartoview\\cartoview\\urls.py", line 17, in <module>
[Mon Aug 15 14:05:10.929962 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]     (r'^apps/', include('cartoview.app_manager.urls')),
[Mon Aug 15 14:05:10.929962 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]   File "C:\\Program Files (x86)\\Cartoview\\Python\\lib\\site-packages\\django-1.6.11-py2.7.egg\\django\\conf\\urls\\__init__.py", line 26, in include
[Mon Aug 15 14:05:10.929962 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]     urlconf_module = import_module(urlconf_module)
[Mon Aug 15 14:05:10.930962 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]   File "C:\\Program Files (x86)\\Cartoview\\Python\\lib\\site-packages\\django-1.6.11-py2.7.egg\\django\\utils\\importlib.py", line 40, in import_module
[Mon Aug 15 14:05:10.930962 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]     __import__(name)
[Mon Aug 15 14:05:10.930962 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]   File "C:\\Program Files (x86)\\Cartoview\\cartoview\\cartoview\\app_manager\\urls.py", line 38, in <module>
[Mon Aug 15 14:05:10.930962 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]     urlpatterns.append(app_url(name))
[Mon Aug 15 14:05:10.930962 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]   File "C:\\Program Files (x86)\\Cartoview\\cartoview\\cartoview\\app_manager\\apps_helper.py", line 17, in app_url
[Mon Aug 15 14:05:10.931962 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]     return url(r'^' + app + '/', include('cartoview.apps.%s.urls' % app), name=app + '_base_url')
[Mon Aug 15 14:05:10.931962 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]   File "C:\\Program Files (x86)\\Cartoview\\Python\\lib\\site-packages\\django-1.6.11-py2.7.egg\\django\\conf\\urls\\__init__.py", line 26, in include
[Mon Aug 15 14:05:10.931962 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]     urlconf_module = import_module(urlconf_module)
[Mon Aug 15 14:05:10.931962 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]   File "C:\\Program Files (x86)\\Cartoview\\Python\\lib\\site-packages\\django-1.6.11-py2.7.egg\\django\\utils\\importlib.py", line 40, in import_module
[Mon Aug 15 14:05:10.931962 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]     __import__(name)
[Mon Aug 15 14:05:10.931962 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]   File "C:\\Program Files (x86)\\Cartoview\\cartoview\\cartoview\\apps\\cartoview_arcgis_feature_server\\urls.py", line 3, in <module>
[Mon Aug 15 14:05:10.932962 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]     from cartoserver.urls import geo_services_rest_patterns
[Mon Aug 15 14:05:10.932962 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]   File "C:\\Program Files (x86)\\Cartoview\\cartoview\\cartoview\\apps\\cartoview_arcgis_feature_server\\cartoserver\\urls.py", line 3, in <module>
[Mon Aug 15 14:05:10.932962 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]     import views
[Mon Aug 15 14:05:10.932962 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]   File "C:\\Program Files (x86)\\Cartoview\\cartoview\\cartoview\\apps\\cartoview_arcgis_feature_server\\cartoserver\\views.py", line 14, in <module>
[Mon Aug 15 14:05:10.933962 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]     from .layers_providers import layers_provider
[Mon Aug 15 14:05:10.933962 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]   File "C:\\Program Files (x86)\\Cartoview\\cartoview\\cartoview\\apps\\cartoview_arcgis_feature_server\\cartoserver\\layers_providers.py", line 76, in <module>
[Mon Aug 15 14:05:10.933962 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]     m = __import__(module)
[Mon Aug 15 14:05:10.934963 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]   File "C:\\Program Files (x86)\\Cartoview\\cartoview\\cartoview\\apps\\cartoview_arcgis_feature_server\\layers_providers.py", line 1, in <module>
[Mon Aug 15 14:05:10.934963 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]     from cartoserver.layers_providers import Provider
[Mon Aug 15 14:05:10.934963 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]   File "C:\\Program Files (x86)\\Cartoview\\cartoview\\cartoview\\apps\\cartoview_arcgis_feature_server\\cartoserver\\layers_providers.py", line 78, in <module>
[Mon Aug 15 14:05:10.934963 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155]     m = getattr(m, comp)
[Mon Aug 15 14:05:10.934963 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61155] AttributeError: 'module' object has no attribute 'layers_providers'
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156] mod_wsgi (pid=81364): Exception occurred processing WSGI script 'C:/Program Files (x86)/Cartoview/Cartoview/cartoview/wsgi.py'., referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156] Traceback (most recent call last):, referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]   File "C:\\Program Files (x86)\\Cartoview\\Python\\lib\\site-packages\\django-1.6.11-py2.7.egg\\django\\core\\handlers\\wsgi.py", line 187, in __call__, referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]     self.load_middleware(), referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]   File "C:\\Program Files (x86)\\Cartoview\\Python\\lib\\site-packages\\django-1.6.11-py2.7.egg\\django\\core\\handlers\\base.py", line 47, in load_middleware, referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]     mw_instance = mw_class(), referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]   File "C:\\Program Files (x86)\\Cartoview\\Python\\lib\\site-packages\\django-1.6.11-py2.7.egg\\django\\middleware\\locale.py", line 24, in __init__, referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]     for url_pattern in get_resolver(None).url_patterns:, referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]   File "C:\\Program Files (x86)\\Cartoview\\Python\\lib\\site-packages\\django-1.6.11-py2.7.egg\\django\\core\\urlresolvers.py", line 365, in url_patterns, referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module), referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]   File "C:\\Program Files (x86)\\Cartoview\\Python\\lib\\site-packages\\django-1.6.11-py2.7.egg\\django\\core\\urlresolvers.py", line 360, in urlconf_module, referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]     self._urlconf_module = import_module(self.urlconf_name), referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]   File "C:\\Program Files (x86)\\Cartoview\\Python\\lib\\site-packages\\django-1.6.11-py2.7.egg\\django\\utils\\importlib.py", line 40, in import_module, referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]     __import__(name), referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]   File "C:\\Program Files (x86)\\Cartoview\\cartoview\\cartoview\\urls.py", line 17, in <module>, referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]     (r'^apps/', include('cartoview.app_manager.urls')),, referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]   File "C:\\Program Files (x86)\\Cartoview\\Python\\lib\\site-packages\\django-1.6.11-py2.7.egg\\django\\conf\\urls\\__init__.py", line 26, in include, referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]     urlconf_module = import_module(urlconf_module), referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]   File "C:\\Program Files (x86)\\Cartoview\\Python\\lib\\site-packages\\django-1.6.11-py2.7.egg\\django\\utils\\importlib.py", line 40, in import_module, referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]     __import__(name), referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]   File "C:\\Program Files (x86)\\Cartoview\\cartoview\\cartoview\\app_manager\\urls.py", line 38, in <module>, referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]     urlpatterns.append(app_url(name)), referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]   File "C:\\Program Files (x86)\\Cartoview\\cartoview\\cartoview\\app_manager\\apps_helper.py", line 17, in app_url, referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]     return url(r'^' + app + '/', include('cartoview.apps.%s.urls' % app), name=app + '_base_url'), referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]   File "C:\\Program Files (x86)\\Cartoview\\Python\\lib\\site-packages\\django-1.6.11-py2.7.egg\\django\\conf\\urls\\__init__.py", line 26, in include, referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]     urlconf_module = import_module(urlconf_module), referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]   File "C:\\Program Files (x86)\\Cartoview\\Python\\lib\\site-packages\\django-1.6.11-py2.7.egg\\django\\utils\\importlib.py", line 40, in import_module, referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]     __import__(name), referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]   File "C:\\Program Files (x86)\\Cartoview\\cartoview\\cartoview\\apps\\cartoview_arcgis_feature_server\\urls.py", line 3, in <module>, referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]     from cartoserver.urls import geo_services_rest_patterns, referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]   File "C:\\Program Files (x86)\\Cartoview\\cartoview\\cartoview\\apps\\cartoview_arcgis_feature_server\\cartoserver\\urls.py", line 3, in <module>, referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]     import views, referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]   File "C:\\Program Files (x86)\\Cartoview\\cartoview\\cartoview\\apps\\cartoview_arcgis_feature_server\\cartoserver\\views.py", line 14, in <module>, referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]     from .layers_providers import layers_provider, referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]   File "C:\\Program Files (x86)\\Cartoview\\cartoview\\cartoview\\apps\\cartoview_arcgis_feature_server\\cartoserver\\layers_providers.py", line 76, in <module>, referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]     m = __import__(module), referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]   File "C:\\Program Files (x86)\\Cartoview\\cartoview\\cartoview\\apps\\cartoview_arcgis_feature_server\\layers_providers.py", line 1, in <module>, referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]     from cartoserver.layers_providers import Provider, referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]   File "C:\\Program Files (x86)\\Cartoview\\cartoview\\cartoview\\apps\\cartoview_arcgis_feature_server\\cartoserver\\layers_providers.py", line 78, in <module>, referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156]     m = getattr(m, comp), referer: http://localhost:4040/
[Mon Aug 15 14:05:11.261045 2016] [wsgi:error] [pid 81364:tid 1148] [client ::1:61156] AttributeError: 'module' object has no attribute 'layers_providers', referer: http://localhost:4040/`

**Comment by kamalseisy** [comment]
After installing any app the apache server should restart automatically and synchronize the database. It seems that this step was failed. so, you should do this manually and try again.
to restart apache, go to Services and restart the service `CARTOVIEW_APACHE_4040`
to synchronize the data base
1. open command line
2. go to C:\Program Files (x86)\Cartoview\cartoview
3. run the command `..\Python\python manage.py syncdb`
